export let applicants = [
    {
      personal_details: {
        name: 'Atharva Kulkarni',
        email: 'mailmenehakulkarni@gmail.com',
        mobile_number: null,
      },
      skills: [
        'Api',
        'Github',
        'Coding',
        'Rest',
        'Sql',
        'Engineering',
        'System',
        'C++',
        'Analysis',
        'Python',
        'Email',
        'Programming',
        'Flask',
        'Pandas',
        'Analytics',
        'Database',
        'C',
      ],
      education: ['B.E in Information Technology'],
      experience: null,
      no_of_pages: 1,
      links: {
        linkedin: 'https://www.linkedin.com/in/atharva-kulkarni-b119b7195/',
        github: [
          'https://github.com/Yashdew/Attendance-Tracker',
          'https://github.com/AK9175/nodejs-mongo',
          'https://github.com/AK9175',
          'https://github.com/SkSumit/Chatistics',
        ],
        leetcode: 'https://leetcode.com/AK9175/',
        codechef: 'https://www.codechef.com/users/ak9175',
        codeforces: null,
        others: [
          'https://chatistics.vercel.app/',
          'https://attendancesknhc.herokuapp.com/',
          'https://genz12.herokuapp.com/',
          'mailto:mailmenehakulkarni@gmail.com',
        ],
      },
      total_experience: 0,
      projects: 'Projects TBC',
      achievements: 'Achievements TBC',
      hobbies: 'Hobbies TBC',
      score: 66,
    },
    {
      personal_details: {
        name: 'JAYESH PADHIAR',
        email: 'jayeshpadhiar20@gmail.com',
        mobile_number: '7218194049',
      },
      skills: [
        'Apis',
        'Policies',
        'Rest',
        'Sql',
        'Physics',
        'Mysql',
        'Mathematics',
        'Ux',
        'Java',
        'C',
        'Github',
        'Chemistry',
        'Controls',
        'Android',
        'Python',
        'Database',
        'Engineering',
        'C++',
        'Email',
      ],
      education: null,
      experience: [
        'FREELANCE WEB DEVELOPER - ESHOPBOX',
        'Jan 21 – Mar 21',
        '•  Successfully delivered a new client-side functionality using',
        'AngularJS that helps end user to modify preferences regarding',
        'UX, Return & Cancellation Policies, Notification Controls etc.',
        'Integrated the web application with the backend using REST APIs',
        '•',
        '•  FREELANCING PLATFORM USING JAVA & SQL',
      ],
      no_of_pages: 1,
      links: {
        linkedin: 'https://www.linkedin.com/in/jayeshpadhiar/',
        github: [
          'https://github.com/JayeshPadhiar/Freelance',
          'https://github.com/JayeshPadhiar/CowinVaccineNotifier',
          'https://github.com/JayeshPadhiar',
        ],
        leetcode: null,
        codechef: null,
        codeforces: null,
        others: [],
      },
      total_experience: 0.0,
      projects: 'Projects TBC',
      achievements: 'Achievements TBC',
      hobbies: 'Hobbies TBC',
      score: 99,
    },
    {
      personal_details: {
        name: 'Yash Dewangan',
        email: 'yashdewangan123456@gmail.com',
        mobile_number: '8602842290',
      },
      skills: [
        'Apis',
        'Api',
        'Rest',
        'Sql',
        'Certification',
        'Statistics',
        'Coding',
        'Information technology',
        'Html',
        'Video',
        'Programming',
        'Apex',
        'Flask',
        'Pandas',
        'C',
        'Github',
        'Ui',
        'Js',
        'Editing',
        'Css',
        'Python',
        'Database',
        'Photography',
        'Django',
        'Engineering',
        'Algorithms',
        'C++',
        'Analysis',
      ],
      education: null,
      experience: [
        'Hack Club  | Lead',
        'April 2020 – Present (Club Repo)',
        '•  Working on building a multiple project for',
        'college.',
        '•  Teach DSA to Juniors.',
        '•  Working collaboratively with a teammate and',
        'brainstorming the new ideas for the project.',
        '•  Responsible for reviewing the code, giving the',
        'demo of the application to the mentors and',
        'fellow developers.',
        '•  Responsible for building backend of the',
        'projects.',
      ],
      no_of_pages: 1,
      links: {
        linkedin: 'https://www.linkedin.com/in/iyashdewangan/',
        github: [
          'https://github.com/Yashdew/Attendance-Tracker',
          'https://github.com/SkSumit/Chatistics',
          'https://github.com/Yashdew',
          'https://github.com/HackClubSKNCOE',
        ],
        leetcode: 'https://leetcode.com/Yashdew/',
        codechef: 'https://www.codechef.com/users/yashdew',
        codeforces: 'http://codeforces.com/profile/yashdewangan123456',
        others: [
          'https://auth.geeksforgeeks.org/user/yashdewangan123456/practice/',
          'https://drive.google.com/file/d/1-UrtlUygeujyDXvZPhI5fW9E1wICL_Qd/view',
          'https://chatistics.vercel.app/',
          'https://attendancesknhc.herokuapp.com/',
          'mailto:yashdewangan123456@gmail.com',
          'https://www.udemy.com/certificate/UC-7185869f-0902-45fa-a8ab-8e818e8ebc88/',
          'https://www.spoj.com/users/yashdew/',
        ],
      },
      total_experience: 0.6,
      projects: 'Projects TBC',
      achievements: 'Achievements TBC',
      hobbies: 'Hobbies TBC',
      score: 88,
    },
    {
      personal_details: {
        name: 'Sumit Kolpekwar',
        email: 'kolsum24@gmail.com',
        mobile_number: '462 2470',
      },
      skills: [
        'Api',
        'Ios',
        'Rest',
        'Sql',
        'Ai',
        'Statistics',
        'Mysql',
        'Html',
        'Marketing',
        'Flask',
        'Pandas',
        'Ux',
        'Testing',
        'Javascript',
        'Ui',
        'Js',
        'Github',
        'Sdlc',
        'Cloud',
        'Css',
        'Teaching',
        'Content',
        'Database',
        'Communication',
        'Engineering',
        'C++',
        'Technical',
      ],
      education: [
        'Bachelor of Engineering in Information, Shrimati Kashibai Navale College Of Engineering',
      ],
      experience: [
        'Book My Appointment | React, Node JS, MongoDB, Redux | Code Demo',
        'Oct 2020 – Nov 2020',
        '• Designed and developed a full-stack web application based on the real-life problem and UX case study',
        '• Followed a SDLC cycle to develop a production level product.',
        '• React as the front-end, NodeJS as the back-end, MongoDB as the database with Firebase for authentication, Jest',
        'for testing, and Github Action for CI/CD, hosted on Heroku.',
        '• Successfully implemented various features from scratch, learning about best practices and popular convention',
        '• Optimized code and improved web-app based on user feedback',
        'Hack Club List | React, Theme UI | Code Demo',
        'Dec 2020 – Dec 2020',
        '• Developed a front-end web application for Hack Club for over 10k members',
        '• Implemented pagination and search functionality',
      ],
      no_of_pages: 1,
      links: {
        linkedin: 'linkedin.com/in/sumitkolpekwar/',
        github: [
          'github.com/SkSumit',
          'https://github.com/HackClubSKNCOE/Clubs',
          'https://github.com/SkSumit/BookMyAppointment',
          'https://hackclubskncoe.github.io/Clubs/',
          'https://github.com/SkSumit',
          'https://github.com/SkSumit/Chatistics',
        ],
        leetcode: 'https://leetcode.com/zeneks24/',
        codechef: null,
        codeforces: null,
        others: [
          'https://chatistics.vercel.app/',
          'http://byapp.herokuapp.com/',
          'mailto:kolsum24@gmail.com',
        ],
      },
      total_experience: 0.4,
      projects: 'Projects TBC',
      achievements: 'Achievements TBC',
      hobbies: 'Hobbies TBC',
      score: 75,
    },
  ],
  job_desc = [
    {
      id: 1,
      company: 'Persistent Systems',
      position: 'Backend Developer',
      location: 'Pune',
      experience: '2-3 Years',
      skills_req: ['Django', 'Python', 'Node', 'Javascript'],
      summary:
        'The candidate should have a thorough knowledge if backend frameworks such as Django, NodeJS. knowledge of REST APIs and Python, JavaScript is needed.',
    },
    {
      id: 2,
      company: 'Jio Platforms',
      position: 'Fullstack Developer',
      location: 'Navi Mumbai',
      experience: '1-2 Years',
      skills_req: [
        'ReactJS',
        'AngularJS',
        'JavaScript',
        'HTML',
        'CSS',
        'Python',
        'NodeJS',
      ],
      summary:
        'The candidate should have a thorough knowledge if backend frameworks such as Django, NodeJS. knowledge of REST APIs and Python, JavaScript is needed.',
    },
    {
      id: 3,
      company: 'eQ Technologic',
      position: 'Backend Developer',
      location: 'Pune',
      experience: '3-4 Years',
      skills_req: ['Django', 'NodeJS'],
      summary:
        'The candidate should have a thorough knowledge if backend frameworks such as Django, NodeJS. knowledge of REST APIs and Python, JavaScript is needed.',
    },
    {
      id: 4,
      company: 'Cognizant',
      position: 'DevOps Engineer',
      location: 'Pune',
      experience: 'None',
      skills_req: ['C++', 'Python'],
      summary:
        'The candidate should have a thorough knowledge if backend frameworks such as Django, NodeJS. knowledge of REST APIs and Python, JavaScript is needed.',
    },
    {
      id: 5,
      company: 'Nice Systems',
      position: 'Software Engineer',
      location: 'Mumbai',
      experience: '1-2 Years',
      skills_req: ['C++', 'Java'],
      summary:
        'The candidate should have a thorough knowledge if backend frameworks such as Django, NodeJS. knowledge of REST APIs and Python, JavaScript is needed.',
    },
  ];
